# Generated by Django 4.0.4 on 2023-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('MusicId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('artist', models.CharField(max_length=500, unique=True)),
                ('year', models.IntegerField()),
                ('web_url', models.CharField(max_length=500, unique=True)),
                ('image_url', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('user_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500, unique=True)),
                ('PasswordSalt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserSongsMappings',
            fields=[
                ('MappingId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('MusicId', models.IntegerField()),
            ],
        ),
    ]
