# Generated by Django 4.0.4 on 2023-04-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicAppBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usersongsmappings',
            table='user_songs_mappings',
        ),
    ]
