# Generated by Django 4.0.4 on 2023-04-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicAppBackend', '0002_alter_music_table_alter_users_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSongsMappings',
            new_name='UserMusicMappings',
        ),
        migrations.AlterModelTable(
            name='usermusicmappings',
            table='user_music_mappings',
        ),
    ]
