# Generated by Django 4.0.4 on 2023-04-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicAppBackend', '0003_rename_usersongsmappings_usermusicmappings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='PasswordSalt',
        ),
    ]
